spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:customer}
    username: ${SPRING_DATASOURCE_USERNAME:usr_customer}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:customer}
    user: ${SPRING_DATASOURCE_USERNAME:usr_customer}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    baseline-on-migrate: true
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
  application:
    env: ${SPRING_APPLICATION_ENV:DEVELOPMENT}
    client:
      product:
        url: ${SPRING_APPLICATION_CLIENT_PRODUCT_URL:http://challenge-api.luizalabs.com/api/product}
        timeout: ${SPRING_APPLICATION_CLIENT_PRODUCT_TIMEOUT:5000}
jwt:
  secret-key: ${JWT_SECRET_KEY:11111111-2222-3333-4444-555555555555}
